### ISSUE TITLE
Panic on mount issue

### ISSUE THREAD

**Issue by dylanwalker** [plexdrive/plexdrive#355] opened 2020-03-31 06:09 UTC
I'm getting a panic when I attempt to mount:

`
d@dbuntu:~$ sudo /usr/local/bin/plexdrive mount -v 2 --root-node-id=*******  -c /home/dwalker/.plexdrive -o allow_other /mnt/plexdrive
[USR/LOCAL/BIN/PLEXDRIVE] [2020-03-30 23:37] INFO   : First cache build process started...
[USR/LOCAL/BIN/PLEXDRIVE] [2020-03-30 23:37] INFO   : Mounting path /mnt/plexdrive
panic: page 134660 already freed

goroutine 19 [running]:
github.com/boltdb/bolt.(*freelist).free(0xc00020e810, 0x5eb9, 0x7fd20ce04000)
        /go/src/github.com/boltdb/bolt/freelist.go:121 +0x2a0
github.com/boltdb/bolt.(*node).spill(0xc0001e4850, 0x0, 0x0)
        /go/src/github.com/boltdb/bolt/node.go:363 +0x206
github.com/boltdb/bolt.(*node).spill(0xc0001e41c0, 0xc000406330, 0xc0001817d0)
        /go/src/github.com/boltdb/bolt/node.go:350 +0xba
github.com/boltdb/bolt.(*Bucket).spill(0xc0003b4380, 0xc000406200, 0xc0001819c8)
        /go/src/github.com/boltdb/bolt/bucket.go:570 +0x473
github.com/boltdb/bolt.(*Bucket).spill(0xc0000bc1d8, 0x17ccb3c2, 0xe64400)
        /go/src/github.com/boltdb/bolt/bucket.go:537 +0x3d5
github.com/boltdb/bolt.(*Tx).Commit(0xc0000bc1c0, 0x0, 0x0)
        /go/src/github.com/boltdb/bolt/tx.go:163 +0xf2
github.com/boltdb/bolt.(*DB).Update(0xc0001fe1e0, 0xc000181c50, 0x0, 0x0)
        /go/src/github.com/boltdb/bolt/db.go:605 +0xf6
github.com/dweidenfeld/plexdrive/drive.(*Cache).BatchUpdateObjects(0xc000190e00, 0xc0003b4340, 0x5, 0x8, 0x5, 0xc0003b4340)
        /go/src/github.com/dweidenfeld/plexdrive/drive/cache.go:282 +0x90
github.com/dweidenfeld/plexdrive/drive.(*Client).checkChanges(0xc0001a0d70, 0x1)
        /go/src/github.com/dweidenfeld/plexdrive/drive/drive.go:156 +0x79f
github.com/dweidenfeld/plexdrive/drive.(*Client).startWatchChanges(0xc0001a0d70, 0xdf8475800)
        /go/src/github.com/dweidenfeld/plexdrive/drive/drive.go:72 +0x34
created by github.com/dweidenfeld/plexdrive/drive.NewClient
        /go/src/github.com/dweidenfeld/plexdrive/drive/drive.go:66 +0x2a8
`

**Comment by felixbuenemann** [comment] 2020-03-31 11:14
Thanks, that is likely caused by a race condition. 

Does it happen reproducible or did it only crash once?

**Comment by felixbuenemann** [comment] 2020-03-31 11:50
@dweidenfeld The docs for boltdb Put state that the value must be valid for the duration of the transaction:

```go

func (c *Cache) BatchUpdateObjects(objects []*APIObject) error {
	err := c.db.Update(func(tx *bolt.Tx) error {
		for _, object := range objects {
			if err := boltUpdateObject(tx, object); nil != err {
				return err
			}
		}
		return nil
	})
```

Looks like GC could free `object` before the Update completes. What do you think?

**Comment by dweidenfeld** [comment] 2020-03-31 12:04
but isn't `c.db.Update()` blocking?

**Comment by felixbuenemann** [comment] 2020-03-31 12:17
My idea was that object is freed on the next iteration of the for loop if gc runs, so the byte slice referencing object.ObjectID could become invalid by the time the transaction (the Update) completes.

I've done some more googling and it looks like this could also be caused by a corrupted bold database.

@dylanwalker Is it possible, that your cache.bolt got corrupted by an unclean shutdown of the server or i/o error in the disc? If that is the case it should work after deleting ~/.plexdrive/cache.bolt and restarting plexdrive.

**Comment by dweidenfeld** [comment] 2020-03-31 12:19
Yeah but in the loop you hold the reference to all objects and only processing one, so the GC should not cause a problem here.

**Comment by felixbuenemann** [comment] 2020-03-31 12:25
But what is passed to b.Put as value is not the, immediate string of object.ObjectID, but a cast to a byte slice that isn't referenced anywhere else, so maybe the slice header gets collected, even though the underlying bytes from the string are still alive.

**Comment by felixbuenemann** [comment] 2020-03-31 12:26
Anyways, if is a reproducible and not caused by corruption a debug build with race detection should be helpful.

**Comment by dylanwalker** [comment] 2020-03-31 16:37
@felixbuenemann I deleted cache.bolt and still get the panic page error, so it isn't a corrupted bolt db. The error is reproducible.

**Comment by felixbuenemann** [comment] 2020-04-01 11:10
@dylanwalker What platform are you running on (eg. Linux/amd64)? I'll build a debug binary with race detection for you, so we can get more details what is going on.

**Comment by dylanwalker** [comment] 2020-04-01 17:06
@felixbuenemann @dweidenfeld thanks! You were both right -- I found that the issue was a corrupted cache.bolt, just not where I expected it to be. When I increased the verbosity, I saw:

dwalker@dbuntu:~$ sudo /usr/local/bin/plexdrive mount -v 3 --root-node-id=********* -c /home/dwalker/.plexdrive -o allow_other /mnt/plexdrive
[USR/LOCAL/BIN/PLEXDRIVE] [2020-04-01 03:30] DEBUG  : verbosity            : DEBUG
[USR/LOCAL/BIN/PLEXDRIVE] [2020-04-01 03:30] DEBUG  : root-node-id         : 0B68xszIkQLsSQW1YMm13dktnNE0
[USR/LOCAL/BIN/PLEXDRIVE] [2020-04-01 03:30] DEBUG  : config               : /home/dwalker/.plexdrive
[USR/LOCAL/BIN/PLEXDRIVE] [2020-04-01 03:30] DEBUG  : cache-file           : /root/.plexdrive/cache.bolt

which indicated that the cache.bolt file was stored in /root/,plexdrive . I'm not sure why this is, as I specified that config should be located under /home/dwalker/,plexdrive , and there was a cache.bolt file there which I deleted. Is the cache.bolt file I found in /root/.plexdrive a temp file?

**Comment by felixbuenemann** [comment] 2020-04-02 11:59
Specifying the config location does not change the location of the cache file, that must be specified separately. Since it is confusing behavior I plan to change that in the future.

**Comment by felixbuenemann** [comment] 2020-04-03 11:35
Closing this issue since it was caused by database corruption and we can't do anything sensible for a panic caused in a third party dependency.

**Closed by felixbuenemann** 2020-04-03 11:35 UTC
Labels: bug
